object Versions {
    const val GRADLE = "7.2.2"

    const val KOTLIN = "1.7.10"
    const val KOTLIN_COROUTINES_ANDROID = "1.3.9"
    const val KOTLIN_SERIALIZATION_JSON = "1.3.2"

    const val CORE_KTX = "1.7.0"
    const val NAVIGATION = "2.5.0"
    const val APP_COMPAT = "1.4.2"
    const val MATERIAL = "1.6.1"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val LIFECYCLE = "2.5.1"
    const val ROOM = "2.3.0"
    const val FRAGMENT_KTX = "1.4.1"
    const val DAGGER_HILT = "2.42"
    const val DAGGER_HILT_LIFECYCLE = "1.0.0-alpha03"
    const val DAGGER_HILT_NAVIGATION = "1.0.0"
    const val RETROFIT = "2.9.0"
    const val RETROFIT_JSON = "0.8.0"
    const val DATASTORE = "1.0.0"
    const val MOSHI = "1.13.0"
    const val MOSHI_CONVERTER = "2.4.0"
    const val GLIDE = "4.13.0"
    const val MAP = "18.1.0"
    const val PLUGIN_SECRETS = "2.0.1"

    const val J_UNIT = "1.1.3"
    const val ESPRESSO = "3.4.0"
}